apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datadog
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev-us-east-1
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-datadog'
    spec:
      project: datadog
      source:
        repoURL: https://github.com/shane-snyder/argo-helm-example.git
        targetRevision: HEAD
        path: 'datadog/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: datadog
      ignoreDifferences:
      - kind: DaemonSet
        jqPathExpressions:
        - .spec.template.metadata.annotations
      syncPolicy:
        syncOptions:
        - RespectIgnoreDifferences=true
