apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-keys
  namespace: kube-system
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: external-secret-store
    kind: ClusterSecretStore
  target:
    name: datadog-secret 
  data:
  - secretKey: api-key
    remoteRef:
      key: datadog
      property: datadog.api_key 
  - secretKey: app-key
    remoteRef:
      key: datadog
      property: datadog.app_key